// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";


export default defineConfig({
  schema: env("PRISMA_SCHEMA"),
  migrations: {
    path: env("PRISMA_MIGRATIONS_PATH"),
    seed: "tsx prisma/seeds/main.ts"
  },
  datasource: {
    url: env("PRISMA_DATABASE_URL"),
  },
});
