import { ApiProperty } from '@nestjs/swagger';
import { HesErrorDto } from './hes-error.dto';

export class HesResponseDto<T> {
  @ApiProperty({
    description:
      'A unique identifier for this request, typically generated by an interceptor',
    example: 'req_1a2b3c4d5e',
  })
  requestId: string; // Unique code per request

  @ApiProperty({
    description: 'Indicates if the API request was successful',
    example: true,
  })
  success: boolean;

  @ApiProperty({
    description:
      'A human-readable message describing the outcome of the request',
    example: 'Operation completed successfully.',
  })
  message: string;

  @ApiProperty({
    description:
      'The actual data payload returned by the API (optional, present on success)',
    required: false,
  })
  data?: T; // Data field is optional, as it won't be present on error

  @ApiProperty({
    description:
      'Details about the error if the request was unsuccessful (optional, present on failure)',
    type: () => HesErrorDto,
    required: false,
  })
  error?: HesErrorDto; // Field for error details

  @ApiProperty({
    description: 'Timestamp when the response was generated',
    example: '2025-12-02T03:00:00.000Z',
  })
  timestamp: string; // Timestamp for the response
}
