services:

  postgres-skeleton-nnp-dev:
    image: postgres:18-alpine
    container_name: postgres-skeleton-nnp-dev
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${EXPOSED_DB_PORT}:${DB_PORT}"
    networks:
      - ${NETWORK_NAME:-skeleton-network}
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  skeleton-network:
    name: ${NETWORK_NAME:-skeleton-network}
    external: true